<a href="https://colab.research.google.com/github/keerthi5083/Sentiment_analysis/blob/main/Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelBinarizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from wordcloud import WordCloud,STOPWORDS
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize,sent_tokenize
from bs4 import BeautifulSoup
import spacy
import re,string,unicodedata
from nltk.tokenize.toktok import ToktokTokenizer
from nltk.stem import LancasterStemmer,WordNetLemmatizer
from sklearn.linear_model import LogisticRegression,SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from textblob import TextBlob
from textblob import Word
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Projects/IMDB Dataset.csv")

In [ ]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
print (df.shape)

(50000, 2)


In [ ]:
print (df.columns)

Index(['review', 'sentiment'], dtype='object')


In [ ]:
df.describe() #summary of dataset

review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [ ]:
print (df.isnull().sum())

review       0
sentiment    0
dtype: int64


In [ ]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [ ]:
#Spliting to training & testing data

train_r=df.review[:30000]
train_s=df.sentiment[:30000]

test_r=df.review[30000:]
test_s=df.sentiment[30000:]

print(train_r.shape,train_s.shape)
print(test_r.shape,test_s.shape)

(30000,) (30000,)
(20000,) (20000,)


In [ ]:
nltk.download('stopwords')
#Normalisating the text

tokenizer=ToktokTokenizer()
stopword_list=nltk.corpus.stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
#Tokenizer - Splits text into smaller units called tokens.
 #"I loved the movie"
 #["I", "loved", "the", "movie"]

#TokTokTokenizer
  #splits text into words clearly
  #keep punctuation seprate
  #works weel with english words

#Stopwords - Loads a list of common english stopwords to remove
 #stopwords = [ is, the, and, of]

#Corpus - A corpus helps computer learn how human language works. Used to train NLP models, analyse language.

In [ ]:
#Removing the html tags
def remove_html(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()

#Removing the square brackets content
def remove_bracket_text(text):
    return re.sub('\\[[^]]*\\]', '', text) #re(regular expression), searches for a pattern in a string and replaces it with something else. pattern - ('\[[^]]), replacement - ''(blank), to clean text

#Combine cleaning steps
def remove_noise_text(text):
    text = remove_html(text)
    text = remove_bracket_text(text)
    return text

#Apply cleaning to the entire dataset
df['review']=df['review'].apply(remove_noise_text)


#BeautifulSoup - Converts HTML into plain text.
#eg - <div>This<b>is good</b>!</div>
   #To - This is good!


In [ ]:
# removing special characters
def remove_special_symbol(text, remove_digits=True):
    pattern=r'[^a-zA-Z0-9\s]'
    text=re.sub(pattern,'',text)
    return text

df['review']=df['review'].apply(remove_special_symbol)

In [ ]:
#Stemming the text (helps ML models treat similar words as the same)
def stemming_sentence(text):
    ps=nltk.porter.PorterStemmer()     # create a ps object
    text= ' '.join([ps.stem(word) for word in text.split()])  #Split the sentence into words(text.split()), Apply stemming to every word, and Join words back into a sentence
    return text

df['review']=df['review'].apply(stemming_sentence)

#eg of stemming
  #running - run
  #amazing - amaz


In [ ]:
#Setting English stopwords
stop=set(stopwords.words('english')) #loads a list of common English stopwords
print(stop)

#removing the stopwords
def remove_stopwords(text, is_lower_case=False):
    tokens = tokenizer.tokenize(text)             #Spliting the text into individual words
    tokens = [token.strip() for token in tokens]  #Removing unnecessary spaces around words
    if is_lower_case:                                           #check if every word is in lowercase else convert it
        filtered_tokens = [token for token in tokens if token not in stopword_list]
    else:
        filtered_tokens = [token for token in tokens if token.lower() not in stopword_list]
    filtered_text = ' '.join(filtered_tokens)
    return filtered_text

df['review']=df['review'].apply(remove_stopwords)

{'of', "hasn't", 'which', "he'll", 'where', 'all', 'their', "weren't", 'wasn', 'how', 'what', "that'll", 'didn', "couldn't", "hadn't", "mightn't", "mustn't", 'me', "you're", "shouldn't", "he'd", 'be', 'himself', 'for', 'over', 'myself', 'o', 'being', 'few', 'against', "aren't", 'once', 'theirs', 'doing', 'more', "she'll", 'about', 'both', 'not', 'some', 'through', 'below', 'this', "wouldn't", 'so', 'don', 'themselves', 'an', "she'd", 'mustn', 'yours', 'them', 'your', 'between', 'too', 'will', "it's", 'my', 'when', 'because', 'do', "she's", 'd', "doesn't", 'ma', 'before', "wasn't", 'most', "it'd", "haven't", "i'd", 're', "we've", 'nor', 'isn', 'yourselves', 'under', 'we', 'itself', 'has', "they've", "didn't", 'during', 'his', 'needn', 'our', 'further', 'those', 'very', "you've", "i've", 'such', 'you', 'out', "i'll", 'at', 'again', "shan't", 'does', 'until', 'did', 'been', 'were', 'no', 'same', 'now', 'yourself', 'am', 'hadn', 'from', 'these', 'ain', 'other', 'and', "you'd", 'y', 'mightn

In [ ]:
#set() - converts the list to a set for faster lookup.

#list comprehension
 #[expression for item in iterable if condition]
  #*expression - what you want to put in the new list.
  #*fpr item in iterable - loop through each item.
  #*if condition - optional filter.

In [ ]:
# Displaying the pre-processed train and test reviews
preprocessed_train_r=df.review[:30000]
preprocessed_train_r[0]   #[0] displaying from very first item

'one review ha mention watch 1 oz episod youll hook right thi exactli happen meth first thing struck oz wa brutal unflinch scene violenc set right word go trust thi show faint heart timid thi show pull punch regard drug sex violenc hardcor classic use wordit call oz nicknam given oswald maximum secur state penitentari focus mainli emerald citi experiment section prison cell glass front face inward privaci high agenda em citi home manyaryan muslim gangsta latino christian italian irish moreso scuffl death stare dodgi deal shadi agreement never far awayi would say main appeal show due fact goe show wouldnt dare forget pretti pictur paint mainstream audienc forget charm forget romanceoz doesnt mess around first episod ever saw struck nasti wa surreal couldnt say wa readi watch develop tast oz got accustom high level graphic violenc violenc injustic crook guard wholl sold nickel inmat wholl kill order get away well manner middl class inmat turn prison bitch due lack street skill prison exp

In [ ]:
preprocessed_test_r=df.review[30000:]
preprocessed_test_r[35005]

'thi kind movi extrem bad cant stop watch becaus keep tell cannot continu thi crappi way end cant know wors jaw 4kind badi honestli think ive onli seen one movi wa wors thi talk religi crap youd end hell lie watch footballgor inde lot well made gore wayth act beyond bad line lousi clich goe storylin onli realli consist sex blood violenc like mani gore moviesif hope mix ichi killer august underground keep look wont find live feed'

In [ ]:
cv=CountVectorizer(min_df=2,max_df=0.9,binary=False,ngram_range=(1,2))

# Parameter explanation:
# min_df = 2
#   → Keep only words/phrases that appear in at least 2 reviews
#   → Removes very rare and noisy words

# max_df = 0.9
#   → Remove words that appear in more than 90% of reviews
#   → Removes extremely common, non-informative words (e.g., "movie", "film")

# binary = False
#   → Use frequency counts (how many times a word appears)
#   → Helps sentiment models learn intensity (e.g., "great great great")

# ngram_range = (1,2)
#   → Use unigrams (1 word) and bigrams (2-word phrases) - A gram means a group of words.
#   → Captures sentiment context like:
#       "good" vs "not good"


#transformed train reviews
cv_train_r=cv.fit_transform(preprocessed_train_r)
#transformed test reviews
cv_test_r=cv.transform(preprocessed_test_r)

print('bow_cv_train:',cv_train_r.shape)
print('bow_cv_test:',cv_test_r.shape)
#vocab=cv.get_feature_names()-toget feature names

bow_cv_train: (30000, 423204)
bow_cv_test: (20000, 423204)


In [ ]:
#Term Frequency – Inverse Document Frequency
#It is a way to convert text into numbers while reducing the importance of very common words.
# TF - How often a word appears in a review.
# IDF - How rare a word is across all reviews.
       #Word appears in many reviews → low importance
       #Word appears in few reviews → high importance
#This helps the model focus on important sentiment words.

#Tfidf vectorizer
tv=TfidfVectorizer(min_df=0.0,max_df=1,use_idf=True,ngram_range=(1,3))
#transformed train reviews
tv_train_r=tv.fit_transform(preprocessed_train_r)
#transformed test reviews
tv_test_r=tv.transform(preprocessed_test_r)
print('Tfidf_train:',tv_train_r.shape)
print('Tfidf_test:',tv_test_r.shape)

Tfidf_train: (30000, 4828698)
Tfidf_test: (20000, 4828698)


In [ ]:
#Labeling the sentiment text to binary (+ve = 1, -ve = 0)

#labeling the sentient data
lb=LabelBinarizer()
#transformed sentiment data
sentiment_data=lb.fit_transform(df['sentiment'])
print(sentiment_data.shape)

(50000, 1)


In [ ]:
#Spliting the sentiment data
train_s=sentiment_data[:30000]
test_s=sentiment_data[30000:]
print(train_s)
print(test_s)

[[1]
 [1]
 [1]
 ...
 [0]
 [1]
 [0]]
[[1]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [ ]:
# Logistic Regression model for both bag of words and tfidf features

#Logistic Regression learns which words indicate positive or negative sentiment and predicts the probability of each review being positive.
#Logistic Regression predicts probability

#training the model
lr_bow = LogisticRegression(
    penalty='l2',                   #A penalty is a rule that prevents the model from becoming too complex.
    max_iter=500,                   #How long the model is allowed to learn
    C=1,                            #How strong the penalty is
    random_state=42                 #Reproducibility
)
#Fitting the model for Bag of words
lr_bow.fit(cv_train_r,train_s)
print(lr_bow)

#notes

#C value	Meaning
#Small C (0.1)	Strong penalty
#Large C (10)	Weak penalty
#C = 1	Balanced (default)

#We keep randomness the same so results are repeatable, comparable, and trustworthy

#Fitting the model for Tfidf
lr_tfidf = LogisticRegression(
    penalty='l2',
    max_iter=500,
    C=1,
    random_state=42
)
lr_tfidf.fit(tv_train_r, train_s)
print(lr_tfidf)


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1, max_iter=500, random_state=42)


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1, max_iter=500, random_state=42)


In [ ]:
lr_bow_predict=lr_bow.predict(cv_test_r)
print(lr_bow_predict)

lr_tfidf_predict=lr_tfidf.predict(tv_test_r)
print(lr_tfidf_predict)

[1 0 0 ... 1 0 0]
[0 0 1 ... 0 1 0]


In [ ]:
#Accuracy for bag of words
lr_bow_score=accuracy_score(test_s,lr_bow_predict)  #compare the orginal test labels with predicted test labels
print("lr_bow_score :",lr_bow_score)
#Accuracy for tfidf features
lr_tfidf_score=accuracy_score(test_s,lr_tfidf_predict)
print("lr_tfidf_score :",lr_tfidf_score)

lr_bow_score : 0.8948
lr_tfidf_score : 0.7387


In [ ]:
#Multinomial Naive Bayes for bag of words and tfidf features

mnb = MultinomialNB()

#Fitting the model for Bag of words
mnb_bow = MultinomialNB()
mnb_bow.fit(cv_train_r, train_s)
print(mnb_bow)

#Fitting the model for Tfidf
mnb_tfidf = MultinomialNB()
mnb_tfidf.fit(tv_train_r, train_s)
print(mnb_tfidf)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()
MultinomialNB()


In [ ]:
#Predicting the models

mnb_bow_predict=mnb_bow.predict(cv_test_r)
print(mnb_bow_predict)

mnb_tfidf_predict=mnb_tfidf.predict(tv_test_r)
print(mnb_tfidf_predict)

[0 0 0 ... 0 1 0]
[0 0 1 ... 0 1 0]


In [ ]:
#Accuracy score
mnb_bow_score=accuracy_score(test_s,mnb_bow_predict)
print("mnb_bow_score :",mnb_bow_score)

mnb_tfidf_score=accuracy_score(test_s,mnb_tfidf_predict)
print("mnb_tfidf_score :",mnb_tfidf_score)

mnb_bow_score : 0.87655
mnb_tfidf_score : 0.73945
